apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-production.yml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "26379"
    port: 26379
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
